custom_standalone_hello:
    path: /
    defaults:
        _controller: CustomStandaloneBundle:Hello:view

custom_standalone_custom:
    path: /custom
    defaults:
        _controller: CustomStandaloneBundle:Custom:view        